modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="potionberries" #mandatory

version="1.0.0" #mandatory

displayName="Potion Berries" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to myself :)" #optional

authors="PyroDeathAdder" #optional

description='''
This is my first mod that i've made.
'''
[[dependencies.potionberries]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.potionberries]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
