package com.pyrodeathadder.potionberries.init;

import com.pyrodeathadder.potionberries.PotionBerries;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.*;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraft.util.LazyValue;
import net.minecraft.util.SoundEvent;
import net.minecraft.util.SoundEvents;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.function.Supplier;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, PotionBerries.MOD_ID);

    public static final RegistryObject<Item> CHRYSOCOLLA_INGOT = ITEMS.register("chrysocolla_ingot", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_NUGGET = ITEMS.register("chrysocolla_nugget", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_INGOT = ITEMS.register("sugilite_ingot", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_NUGGET = ITEMS.register("sugilite_nugget", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_INGOT = ITEMS.register("erythrite_ingot", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_NUGGET = ITEMS.register("erythrite_nugget", () -> new Item(new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));

    //Tools
    //chrysocolla
    public static final RegistryObject<Item> CHRYSOCOLLA_SWORD = ITEMS.register("chrysocolla_sword", () -> new SwordItem(CustomItemTier.CHRYSOCOLLA, 7, -2.4f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_PICKAXE = ITEMS.register("chrysocolla_pickaxe", () -> new PickaxeItem(CustomItemTier.CHRYSOCOLLA, 5,-2.8f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_AXE = ITEMS.register("chrysocolla_axe", () -> new AxeItem(CustomItemTier.CHRYSOCOLLA,9,-3, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_SHOVEL = ITEMS.register("chrysocolla_shovel", () -> new ShovelItem(CustomItemTier.CHRYSOCOLLA,5.5f,-3, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_HOE = ITEMS.register("chrysocolla_hoe", () -> new HoeItem(CustomItemTier.CHRYSOCOLLA,-3,new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    //sugilite
    public static final RegistryObject<Item> SUGILITE_SWORD = ITEMS.register("sugilite_sword", () -> new SwordItem(CustomItemTier.SUGILITE, 8, -2.4f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_PICKAXE = ITEMS.register("sugilite_pickaxe", () -> new PickaxeItem(CustomItemTier.SUGILITE, 7,-2.8f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_AXE = ITEMS.register("sugilite_axe", () -> new AxeItem(CustomItemTier.SUGILITE,9,-2.9f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_SHOVEL = ITEMS.register("sugilite_shovel", () -> new ShovelItem(CustomItemTier.SUGILITE,6.0f,-3, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_HOE = ITEMS.register("sugilite_hoe", () -> new HoeItem(CustomItemTier.SUGILITE,-3,new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    //erythrite
    public static final RegistryObject<Item> ERYTHRITE_SWORD = ITEMS.register("erythrite_sword", () -> new SwordItem(CustomItemTier.ERYTHRITE, 9, -2.3f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_PICKAXE = ITEMS.register("erythrite_pickaxe", () -> new PickaxeItem(CustomItemTier.ERYTHRITE, 7,-2.8f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_AXE = ITEMS.register("erythrite_axe", () -> new AxeItem(CustomItemTier.ERYTHRITE,10,-2.9f, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_SHOVEL = ITEMS.register("erythrite_shovel", () -> new ShovelItem(CustomItemTier.ERYTHRITE,6.5f,-3, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_HOE = ITEMS.register("erythrite_hoe", () -> new HoeItem(CustomItemTier.ERYTHRITE,-3,new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));

    //Armor
    //chrysocolla
    public static final RegistryObject<Item> CHRYSOCOLLA_HELMET = ITEMS.register("chrysocolla_helmet", () -> new ArmorItem(CustomArmourMaterial.CHRYSOCOLLA, EquipmentSlotType.HEAD, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_CHESTPLATE = ITEMS.register("chrysocolla_chestplate", () -> new ArmorItem(CustomArmourMaterial.CHRYSOCOLLA, EquipmentSlotType.CHEST, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_LEGGINGS = ITEMS.register("chrysocolla_leggings", () -> new ArmorItem(CustomArmourMaterial.CHRYSOCOLLA, EquipmentSlotType.LEGS, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> CHRYSOCOLLA_BOOTS = ITEMS.register("chrysocolla_boots", () -> new ArmorItem(CustomArmourMaterial.CHRYSOCOLLA, EquipmentSlotType.FEET, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    //sugilite
    public static final RegistryObject<Item> SUGILITE_HELMET = ITEMS.register("sugilite_helmet", () -> new ArmorItem(CustomArmourMaterial.SUGILITE, EquipmentSlotType.HEAD, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_CHESTPLATE = ITEMS.register("sugilite_chestplate", () -> new ArmorItem(CustomArmourMaterial.SUGILITE, EquipmentSlotType.CHEST, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_LEGGINGS = ITEMS.register("sugilite_leggings", () -> new ArmorItem(CustomArmourMaterial.SUGILITE, EquipmentSlotType.LEGS, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SUGILITE_BOOTS = ITEMS.register("sugilite_boots", () -> new ArmorItem(CustomArmourMaterial.SUGILITE, EquipmentSlotType.FEET, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    //chrysocolla
    public static final RegistryObject<Item> ERYTHRITE_HELMET = ITEMS.register("erythrite_helmet", () -> new ArmorItem(CustomArmourMaterial.ERYTHRITE, EquipmentSlotType.HEAD, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_CHESTPLATE = ITEMS.register("erythrite_chestplate", () -> new ArmorItem(CustomArmourMaterial.ERYTHRITE, EquipmentSlotType.CHEST, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_LEGGINGS = ITEMS.register("erythrite_leggings", () -> new ArmorItem(CustomArmourMaterial.ERYTHRITE, EquipmentSlotType.LEGS, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> ERYTHRITE_BOOTS = ITEMS.register("erythrite_boots", () -> new ArmorItem(CustomArmourMaterial.ERYTHRITE, EquipmentSlotType.FEET, new Item.Properties().group(PotionBerries.PotionBerriesItemGroup.instance)));


    //berries
    public static final RegistryObject<Item> NIGHT_VISION_SWEET_BERRIES_1 = ITEMS.register("night_vision_sweet_berries_1", () -> new BlockItem(BlockInit.NIGHT_VISION_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.NIGHT_VISION, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_NIGHT_VISION_SWEET_BERRIES_1 = ITEMS.register("long_night_vision_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_NIGHT_VISION_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.NIGHT_VISION, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> INVISIBILITY_SWEET_BERRIES_1 = ITEMS.register("invisibility_sweet_berries_1", () -> new BlockItem(BlockInit.INVISIBILITY_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INVISIBILITY, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_INVISIBILITY_SWEET_BERRIES_1 = ITEMS.register("long_invisibility_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_INVISIBILITY_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INVISIBILITY, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LEAPING_SWEET_BERRIES_1 = ITEMS.register("leaping_sweet_berries_1", () -> new BlockItem(BlockInit.LEAPING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.JUMP_BOOST, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_LEAPING_SWEET_BERRIES_1 = ITEMS.register("long_leaping_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_LEAPING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.JUMP_BOOST, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_LEAPING_SWEET_BERRIES_1 = ITEMS.register("strong_leaping_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_LEAPING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.JUMP_BOOST, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> FIRE_RESISTANCE_SWEET_BERRIES_1 = ITEMS.register("fire_resistance_sweet_berries_1", () -> new BlockItem(BlockInit.FIRE_RESISTANCE_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_FIRE_RESISTANCE_SWEET_BERRIES_1 = ITEMS.register("long_fire_resistance_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_FIRE_RESISTANCE_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SPEED_SWEET_BERRIES_1 = ITEMS.register("speed_sweet_berries_1", () -> new BlockItem(BlockInit.SPEED_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SPEED, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SPEED_SWEET_BERRIES_1 = ITEMS.register("long_speed_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_SPEED_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SPEED, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SPEED_SWEET_BERRIES_1 = ITEMS.register("strong_speed_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_SPEED_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SPEED, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOWNESS_SWEET_BERRIES_1 = ITEMS.register("slowness_sweet_berries_1", () -> new BlockItem(BlockInit.SLOWNESS_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOWNESS_SWEET_BERRIES_1 = ITEMS.register("long_slowness_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_SLOWNESS_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 1600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SLOWNESS_SWEET_BERRIES_1 = ITEMS.register("strong_slowness_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_SLOWNESS_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> TURTLE_MASTER_SWEET_BERRIES_1 = ITEMS.register("turtle_master_sweet_berries_1", () -> new BlockItem(BlockInit.TURTLE_MASTER_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.45f).effect(new EffectInstance(Effects.RESISTANCE, 133, 3), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_TURTLE_MASTER_SWEET_BERRIES_1 = ITEMS.register("long_turtle_master_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_TURTLE_MASTER_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 266, 4), 0.6f).effect(new EffectInstance(Effects.RESISTANCE, 266, 3), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_TURTLE_MASTER_SWEET_BERRIES_1 = ITEMS.register("strong_turtle_master_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_TURTLE_MASTER_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 6), 0.75f).effect(new EffectInstance(Effects.RESISTANCE, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WATER_BREATHING_SWEET_BERRIES_1 = ITEMS.register("water_breathing_sweet_berries_1", () -> new BlockItem(BlockInit.WATER_BREATHING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WATER_BREATHING, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WATER_BREATHING_SWEET_BERRIES_1 = ITEMS.register("long_water_breathing_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_WATER_BREATHING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WATER_BREATHING, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HEALING_SWEET_BERRIES_1 = ITEMS.register("healing_sweet_berries_1", () -> new BlockItem(BlockInit.HEALING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HEALING_SWEET_BERRIES_1 = ITEMS.register("strong_healing_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_HEALING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HARMING_SWEET_BERRIES_1 = ITEMS.register("harming_sweet_berries_1", () -> new BlockItem(BlockInit.HARMING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HARMING_SWEET_BERRIES_1 = ITEMS.register("strong_harming_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_HARMING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> POISON_SWEET_BERRIES_1 = ITEMS.register("poison_sweet_berries_1", () -> new BlockItem(BlockInit.POISON_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.POISON, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_POISON_SWEET_BERRIES_1 = ITEMS.register("long_poison_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_POISON_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.POISON, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_POISON_SWEET_BERRIES_1 = ITEMS.register("strong_poison_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_POISON_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.POISON, 144, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> REGENERATION_SWEET_BERRIES_1 = ITEMS.register("regeneration_sweet_berries_1", () -> new BlockItem(BlockInit.REGENERATION_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.REGENERATION, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_REGENERATION_SWEET_BERRIES_1 = ITEMS.register("long_regeneration_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_REGENERATION_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.REGENERATION, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_REGENERATION_SWEET_BERRIES_1 = ITEMS.register("strong_regeneration_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_REGENERATION_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.REGENERATION, 150, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRENGTH_SWEET_BERRIES_1 = ITEMS.register("strength_sweet_berries_1", () -> new BlockItem(BlockInit.STRENGTH_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.STRENGTH, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_STRENGTH_SWEET_BERRIES_1 = ITEMS.register("long_strength_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_STRENGTH_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.STRENGTH, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_STRENGTH_SWEET_BERRIES_1 = ITEMS.register("strong_strength_sweet_berries_1", () -> new BlockItem(BlockInit.STRONG_STRENGTH_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.STRENGTH, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WEAKNESS_SWEET_BERRIES_1 = ITEMS.register("weakness_sweet_berries_1", () -> new BlockItem(BlockInit.WEAKNESS_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WEAKNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WEAKNESS_SWEET_BERRIES_1 = ITEMS.register("long_weakness_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_WEAKNESS_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WEAKNESS, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOW_FALLING_SWEET_BERRIES_1 = ITEMS.register("slow_falling_sweet_berries_1", () -> new BlockItem(BlockInit.SLOW_FALLING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOW_FALLING, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOW_FALLING_SWEET_BERRIES_1 = ITEMS.register("long_slow_falling_sweet_berries_1", () -> new BlockItem(BlockInit.LONG_SLOW_FALLING_BERRY_BUSH_1.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOW_FALLING, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));

    public static final RegistryObject<Item> NIGHT_VISION_SWEET_BERRIES_2 = ITEMS.register("night_vision_sweet_berries_2", () -> new BlockItem(BlockInit.NIGHT_VISION_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.NIGHT_VISION, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_NIGHT_VISION_SWEET_BERRIES_2 = ITEMS.register("long_night_vision_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_NIGHT_VISION_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.NIGHT_VISION, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> INVISIBILITY_SWEET_BERRIES_2 = ITEMS.register("invisibility_sweet_berries_2", () -> new BlockItem(BlockInit.INVISIBILITY_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INVISIBILITY, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_INVISIBILITY_SWEET_BERRIES_2 = ITEMS.register("long_invisibility_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_INVISIBILITY_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INVISIBILITY, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LEAPING_SWEET_BERRIES_2 = ITEMS.register("leaping_sweet_berries_2", () -> new BlockItem(BlockInit.LEAPING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.JUMP_BOOST, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_LEAPING_SWEET_BERRIES_2 = ITEMS.register("long_leaping_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_LEAPING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.JUMP_BOOST, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_LEAPING_SWEET_BERRIES_2 = ITEMS.register("strong_leaping_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_LEAPING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.JUMP_BOOST, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> FIRE_RESISTANCE_SWEET_BERRIES_2 = ITEMS.register("fire_resistance_sweet_berries_2", () -> new BlockItem(BlockInit.FIRE_RESISTANCE_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_FIRE_RESISTANCE_SWEET_BERRIES_2 = ITEMS.register("long_fire_resistance_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_FIRE_RESISTANCE_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SPEED_SWEET_BERRIES_2 = ITEMS.register("speed_sweet_berries_2", () -> new BlockItem(BlockInit.SPEED_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SPEED, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SPEED_SWEET_BERRIES_2 = ITEMS.register("long_speed_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_SPEED_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SPEED, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SPEED_SWEET_BERRIES_2 = ITEMS.register("strong_speed_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_SPEED_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SPEED, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOWNESS_SWEET_BERRIES_2 = ITEMS.register("slowness_sweet_berries_2", () -> new BlockItem(BlockInit.SLOWNESS_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOWNESS_SWEET_BERRIES_2 = ITEMS.register("long_slowness_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_SLOWNESS_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 1600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SLOWNESS_SWEET_BERRIES_2 = ITEMS.register("strong_slowness_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_SLOWNESS_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> TURTLE_MASTER_SWEET_BERRIES_2 = ITEMS.register("turtle_master_sweet_berries_2", () -> new BlockItem(BlockInit.TURTLE_MASTER_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.45f).effect(new EffectInstance(Effects.RESISTANCE, 133, 3), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_TURTLE_MASTER_SWEET_BERRIES_2 = ITEMS.register("long_turtle_master_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_TURTLE_MASTER_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 266, 4), 0.6f).effect(new EffectInstance(Effects.RESISTANCE, 266, 3), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_TURTLE_MASTER_SWEET_BERRIES_2 = ITEMS.register("strong_turtle_master_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_TURTLE_MASTER_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 6), 0.75f).effect(new EffectInstance(Effects.RESISTANCE, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WATER_BREATHING_SWEET_BERRIES_2 = ITEMS.register("water_breathing_sweet_berries_2", () -> new BlockItem(BlockInit.WATER_BREATHING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WATER_BREATHING, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WATER_BREATHING_SWEET_BERRIES_2 = ITEMS.register("long_water_breathing_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_WATER_BREATHING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WATER_BREATHING, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HEALING_SWEET_BERRIES_2 = ITEMS.register("healing_sweet_berries_2", () -> new BlockItem(BlockInit.HEALING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HEALING_SWEET_BERRIES_2 = ITEMS.register("strong_healing_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_HEALING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HARMING_SWEET_BERRIES_2 = ITEMS.register("harming_sweet_berries_2", () -> new BlockItem(BlockInit.HARMING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HARMING_SWEET_BERRIES_2 = ITEMS.register("strong_harming_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_HARMING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> POISON_SWEET_BERRIES_2 = ITEMS.register("poison_sweet_berries_2", () -> new BlockItem(BlockInit.POISON_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.POISON, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_POISON_SWEET_BERRIES_2 = ITEMS.register("long_poison_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_POISON_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.POISON, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_POISON_SWEET_BERRIES_2 = ITEMS.register("strong_poison_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_POISON_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.POISON, 144, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> REGENERATION_SWEET_BERRIES_2 = ITEMS.register("regeneration_sweet_berries_2", () -> new BlockItem(BlockInit.REGENERATION_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.REGENERATION, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_REGENERATION_SWEET_BERRIES_2 = ITEMS.register("long_regeneration_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_REGENERATION_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.REGENERATION, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_REGENERATION_SWEET_BERRIES_2 = ITEMS.register("strong_regeneration_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_REGENERATION_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.REGENERATION, 150, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRENGTH_SWEET_BERRIES_2 = ITEMS.register("strength_sweet_berries_2", () -> new BlockItem(BlockInit.STRENGTH_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.STRENGTH, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_STRENGTH_SWEET_BERRIES_2 = ITEMS.register("long_strength_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_STRENGTH_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.STRENGTH, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_STRENGTH_SWEET_BERRIES_2 = ITEMS.register("strong_strength_sweet_berries_2", () -> new BlockItem(BlockInit.STRONG_STRENGTH_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.STRENGTH, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WEAKNESS_SWEET_BERRIES_2 = ITEMS.register("weakness_sweet_berries_2", () -> new BlockItem(BlockInit.WEAKNESS_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WEAKNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WEAKNESS_SWEET_BERRIES_2 = ITEMS.register("long_weakness_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_WEAKNESS_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WEAKNESS, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOW_FALLING_SWEET_BERRIES_2 = ITEMS.register("slow_falling_sweet_berries_2", () -> new BlockItem(BlockInit.SLOW_FALLING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOW_FALLING, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOW_FALLING_SWEET_BERRIES_2 = ITEMS.register("long_slow_falling_sweet_berries_2", () -> new BlockItem(BlockInit.LONG_SLOW_FALLING_BERRY_BUSH_2.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOW_FALLING, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));

    public static final RegistryObject<Item> NIGHT_VISION_SWEET_BERRIES_3 = ITEMS.register("night_vision_sweet_berries_3", () -> new BlockItem(BlockInit.NIGHT_VISION_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.NIGHT_VISION, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_NIGHT_VISION_SWEET_BERRIES_3 = ITEMS.register("long_night_vision_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_NIGHT_VISION_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.NIGHT_VISION, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> INVISIBILITY_SWEET_BERRIES_3 = ITEMS.register("invisibility_sweet_berries_3", () -> new BlockItem(BlockInit.INVISIBILITY_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INVISIBILITY, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_INVISIBILITY_SWEET_BERRIES_3 = ITEMS.register("long_invisibility_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_INVISIBILITY_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INVISIBILITY, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LEAPING_SWEET_BERRIES_3 = ITEMS.register("leaping_sweet_berries_3", () -> new BlockItem(BlockInit.LEAPING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.JUMP_BOOST, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_LEAPING_SWEET_BERRIES_3 = ITEMS.register("long_leaping_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_LEAPING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.JUMP_BOOST, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_LEAPING_SWEET_BERRIES_3 = ITEMS.register("strong_leaping_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_LEAPING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.JUMP_BOOST, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> FIRE_RESISTANCE_SWEET_BERRIES_3 = ITEMS.register("fire_resistance_sweet_berries_3", () -> new BlockItem(BlockInit.FIRE_RESISTANCE_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_FIRE_RESISTANCE_SWEET_BERRIES_3 = ITEMS.register("long_fire_resistance_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_FIRE_RESISTANCE_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SPEED_SWEET_BERRIES_3 = ITEMS.register("speed_sweet_berries_3", () -> new BlockItem(BlockInit.SPEED_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SPEED, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SPEED_SWEET_BERRIES_3 = ITEMS.register("long_speed_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_SPEED_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SPEED, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SPEED_SWEET_BERRIES_3 = ITEMS.register("strong_speed_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_SPEED_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SPEED, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOWNESS_SWEET_BERRIES_3 = ITEMS.register("slowness_sweet_berries_3", () -> new BlockItem(BlockInit.SLOWNESS_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOWNESS_SWEET_BERRIES_3 = ITEMS.register("long_slowness_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_SLOWNESS_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 1600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SLOWNESS_SWEET_BERRIES_3 = ITEMS.register("strong_slowness_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_SLOWNESS_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> TURTLE_MASTER_SWEET_BERRIES_3 = ITEMS.register("turtle_master_sweet_berries_3", () -> new BlockItem(BlockInit.TURTLE_MASTER_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.45f).effect(new EffectInstance(Effects.RESISTANCE, 133, 3), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_TURTLE_MASTER_SWEET_BERRIES_3 = ITEMS.register("long_turtle_master_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_TURTLE_MASTER_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 266, 4), 0.6f).effect(new EffectInstance(Effects.RESISTANCE, 266, 3), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_TURTLE_MASTER_SWEET_BERRIES_3 = ITEMS.register("strong_turtle_master_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_TURTLE_MASTER_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 6), 0.75f).effect(new EffectInstance(Effects.RESISTANCE, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WATER_BREATHING_SWEET_BERRIES_3 = ITEMS.register("water_breathing_sweet_berries_3", () -> new BlockItem(BlockInit.WATER_BREATHING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WATER_BREATHING, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WATER_BREATHING_SWEET_BERRIES_3 = ITEMS.register("long_water_breathing_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_WATER_BREATHING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WATER_BREATHING, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HEALING_SWEET_BERRIES_3 = ITEMS.register("healing_sweet_berries_3", () -> new BlockItem(BlockInit.HEALING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HEALING_SWEET_BERRIES_3 = ITEMS.register("strong_healing_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_HEALING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HARMING_SWEET_BERRIES_3 = ITEMS.register("harming_sweet_berries_3", () -> new BlockItem(BlockInit.HARMING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HARMING_SWEET_BERRIES_3 = ITEMS.register("strong_harming_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_HARMING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> POISON_SWEET_BERRIES_3 = ITEMS.register("poison_sweet_berries_3", () -> new BlockItem(BlockInit.POISON_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.POISON, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_POISON_SWEET_BERRIES_3 = ITEMS.register("long_poison_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_POISON_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.POISON, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_POISON_SWEET_BERRIES_3 = ITEMS.register("strong_poison_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_POISON_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.POISON, 144, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> REGENERATION_SWEET_BERRIES_3 = ITEMS.register("regeneration_sweet_berries_3", () -> new BlockItem(BlockInit.REGENERATION_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.REGENERATION, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_REGENERATION_SWEET_BERRIES_3 = ITEMS.register("long_regeneration_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_REGENERATION_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.REGENERATION, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_REGENERATION_SWEET_BERRIES_3 = ITEMS.register("strong_regeneration_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_REGENERATION_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.REGENERATION, 150, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRENGTH_SWEET_BERRIES_3 = ITEMS.register("strength_sweet_berries_3", () -> new BlockItem(BlockInit.STRENGTH_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.STRENGTH, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_STRENGTH_SWEET_BERRIES_3 = ITEMS.register("long_strength_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_STRENGTH_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.STRENGTH, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_STRENGTH_SWEET_BERRIES_3 = ITEMS.register("strong_strength_sweet_berries_3", () -> new BlockItem(BlockInit.STRONG_STRENGTH_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.STRENGTH, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WEAKNESS_SWEET_BERRIES_3 = ITEMS.register("weakness_sweet_berries_3", () -> new BlockItem(BlockInit.WEAKNESS_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WEAKNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WEAKNESS_SWEET_BERRIES_3 = ITEMS.register("long_weakness_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_WEAKNESS_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WEAKNESS, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOW_FALLING_SWEET_BERRIES_3 = ITEMS.register("slow_falling_sweet_berries_3", () -> new BlockItem(BlockInit.SLOW_FALLING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOW_FALLING, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOW_FALLING_SWEET_BERRIES_3 = ITEMS.register("long_slow_falling_sweet_berries_3", () -> new BlockItem(BlockInit.LONG_SLOW_FALLING_BERRY_BUSH_3.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOW_FALLING, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));

    public static final RegistryObject<Item> NIGHT_VISION_SWEET_BERRIES_4 = ITEMS.register("night_vision_sweet_berries_4", () -> new BlockItem(BlockInit.NIGHT_VISION_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.NIGHT_VISION, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_NIGHT_VISION_SWEET_BERRIES_4 = ITEMS.register("long_night_vision_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_NIGHT_VISION_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.NIGHT_VISION, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> INVISIBILITY_SWEET_BERRIES_4 = ITEMS.register("invisibility_sweet_berries_4", () -> new BlockItem(BlockInit.INVISIBILITY_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INVISIBILITY, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_INVISIBILITY_SWEET_BERRIES_4 = ITEMS.register("long_invisibility_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_INVISIBILITY_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INVISIBILITY, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LEAPING_SWEET_BERRIES_4 = ITEMS.register("leaping_sweet_berries_4", () -> new BlockItem(BlockInit.LEAPING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.JUMP_BOOST, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_LEAPING_SWEET_BERRIES_4 = ITEMS.register("long_leaping_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_LEAPING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.JUMP_BOOST, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_LEAPING_SWEET_BERRIES_4 = ITEMS.register("strong_leaping_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_LEAPING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.JUMP_BOOST, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> FIRE_RESISTANCE_SWEET_BERRIES_4 = ITEMS.register("fire_resistance_sweet_berries_4", () -> new BlockItem(BlockInit.FIRE_RESISTANCE_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_FIRE_RESISTANCE_SWEET_BERRIES_4 = ITEMS.register("long_fire_resistance_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_FIRE_RESISTANCE_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SPEED_SWEET_BERRIES_4 = ITEMS.register("speed_sweet_berries_4", () -> new BlockItem(BlockInit.SPEED_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SPEED, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SPEED_SWEET_BERRIES_4 = ITEMS.register("long_speed_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_SPEED_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SPEED, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SPEED_SWEET_BERRIES_4 = ITEMS.register("strong_speed_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_SPEED_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SPEED, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOWNESS_SWEET_BERRIES_4 = ITEMS.register("slowness_sweet_berries_4", () -> new BlockItem(BlockInit.SLOWNESS_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOWNESS_SWEET_BERRIES_4 = ITEMS.register("long_slowness_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_SLOWNESS_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 1600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SLOWNESS_SWEET_BERRIES_4 = ITEMS.register("strong_slowness_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_SLOWNESS_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> TURTLE_MASTER_SWEET_BERRIES_4 = ITEMS.register("turtle_master_sweet_berries_4", () -> new BlockItem(BlockInit.TURTLE_MASTER_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.45f).effect(new EffectInstance(Effects.RESISTANCE, 133, 3), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_TURTLE_MASTER_SWEET_BERRIES_4 = ITEMS.register("long_turtle_master_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_TURTLE_MASTER_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 266, 4), 0.6f).effect(new EffectInstance(Effects.RESISTANCE, 266, 3), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_TURTLE_MASTER_SWEET_BERRIES_4 = ITEMS.register("strong_turtle_master_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_TURTLE_MASTER_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 6), 0.75f).effect(new EffectInstance(Effects.RESISTANCE, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WATER_BREATHING_SWEET_BERRIES_4 = ITEMS.register("water_breathing_sweet_berries_4", () -> new BlockItem(BlockInit.WATER_BREATHING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WATER_BREATHING, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WATER_BREATHING_SWEET_BERRIES_4 = ITEMS.register("long_water_breathing_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_WATER_BREATHING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WATER_BREATHING, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HEALING_SWEET_BERRIES_4 = ITEMS.register("healing_sweet_berries_4", () -> new BlockItem(BlockInit.HEALING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HEALING_SWEET_BERRIES_4 = ITEMS.register("strong_healing_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_HEALING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HARMING_SWEET_BERRIES_4 = ITEMS.register("harming_sweet_berries_4", () -> new BlockItem(BlockInit.HARMING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HARMING_SWEET_BERRIES_4 = ITEMS.register("strong_harming_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_HARMING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> POISON_SWEET_BERRIES_4 = ITEMS.register("poison_sweet_berries_4", () -> new BlockItem(BlockInit.POISON_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.POISON, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_POISON_SWEET_BERRIES_4 = ITEMS.register("long_poison_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_POISON_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.POISON, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_POISON_SWEET_BERRIES_4 = ITEMS.register("strong_poison_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_POISON_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.POISON, 144, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> REGENERATION_SWEET_BERRIES_4 = ITEMS.register("regeneration_sweet_berries_4", () -> new BlockItem(BlockInit.REGENERATION_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.REGENERATION, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_REGENERATION_SWEET_BERRIES_4 = ITEMS.register("long_regeneration_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_REGENERATION_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.REGENERATION, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_REGENERATION_SWEET_BERRIES_4 = ITEMS.register("strong_regeneration_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_REGENERATION_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.REGENERATION, 150, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRENGTH_SWEET_BERRIES_4 = ITEMS.register("strength_sweet_berries_4", () -> new BlockItem(BlockInit.STRENGTH_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.STRENGTH, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_STRENGTH_SWEET_BERRIES_4 = ITEMS.register("long_strength_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_STRENGTH_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.STRENGTH, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_STRENGTH_SWEET_BERRIES_4 = ITEMS.register("strong_strength_sweet_berries_4", () -> new BlockItem(BlockInit.STRONG_STRENGTH_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.STRENGTH, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WEAKNESS_SWEET_BERRIES_4 = ITEMS.register("weakness_sweet_berries_4", () -> new BlockItem(BlockInit.WEAKNESS_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WEAKNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WEAKNESS_SWEET_BERRIES_4 = ITEMS.register("long_weakness_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_WEAKNESS_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WEAKNESS, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOW_FALLING_SWEET_BERRIES_4 = ITEMS.register("slow_falling_sweet_berries_4", () -> new BlockItem(BlockInit.SLOW_FALLING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOW_FALLING, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOW_FALLING_SWEET_BERRIES_4 = ITEMS.register("long_slow_falling_sweet_berries_4", () -> new BlockItem(BlockInit.LONG_SLOW_FALLING_BERRY_BUSH_4.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOW_FALLING, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));

    public static final RegistryObject<Item> NIGHT_VISION_SWEET_BERRIES_5 = ITEMS.register("night_vision_sweet_berries_5", () -> new BlockItem(BlockInit.NIGHT_VISION_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.NIGHT_VISION, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_NIGHT_VISION_SWEET_BERRIES_5 = ITEMS.register("long_night_vision_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_NIGHT_VISION_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.NIGHT_VISION, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> INVISIBILITY_SWEET_BERRIES_5 = ITEMS.register("invisibility_sweet_berries_5", () -> new BlockItem(BlockInit.INVISIBILITY_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INVISIBILITY, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_INVISIBILITY_SWEET_BERRIES_5 = ITEMS.register("long_invisibility_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_INVISIBILITY_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INVISIBILITY, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LEAPING_SWEET_BERRIES_5 = ITEMS.register("leaping_sweet_berries_5", () -> new BlockItem(BlockInit.LEAPING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.JUMP_BOOST, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_LEAPING_SWEET_BERRIES_5 = ITEMS.register("long_leaping_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_LEAPING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.JUMP_BOOST, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_LEAPING_SWEET_BERRIES_5 = ITEMS.register("strong_leaping_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_LEAPING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.JUMP_BOOST, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> FIRE_RESISTANCE_SWEET_BERRIES_5 = ITEMS.register("fire_resistance_sweet_berries_5", () -> new BlockItem(BlockInit.FIRE_RESISTANCE_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_FIRE_RESISTANCE_SWEET_BERRIES_5 = ITEMS.register("long_fire_resistance_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_FIRE_RESISTANCE_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.FIRE_RESISTANCE, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SPEED_SWEET_BERRIES_5 = ITEMS.register("speed_sweet_berries_5", () -> new BlockItem(BlockInit.SPEED_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SPEED, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SPEED_SWEET_BERRIES_5 = ITEMS.register("long_speed_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_SPEED_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SPEED, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SPEED_SWEET_BERRIES_5 = ITEMS.register("strong_speed_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_SPEED_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SPEED, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOWNESS_SWEET_BERRIES_5 = ITEMS.register("slowness_sweet_berries_5", () -> new BlockItem(BlockInit.SLOWNESS_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOWNESS_SWEET_BERRIES_5 = ITEMS.register("long_slowness_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_SLOWNESS_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 1600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_SLOWNESS_SWEET_BERRIES_5 = ITEMS.register("strong_slowness_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_SLOWNESS_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> TURTLE_MASTER_SWEET_BERRIES_5 = ITEMS.register("turtle_master_sweet_berries_5", () -> new BlockItem(BlockInit.TURTLE_MASTER_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOWNESS, 133, 4), 0.45f).effect(new EffectInstance(Effects.RESISTANCE, 133, 3), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_TURTLE_MASTER_SWEET_BERRIES_5 = ITEMS.register("long_turtle_master_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_TURTLE_MASTER_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.SLOWNESS, 266, 4), 0.6f).effect(new EffectInstance(Effects.RESISTANCE, 266, 3), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_TURTLE_MASTER_SWEET_BERRIES_5 = ITEMS.register("strong_turtle_master_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_TURTLE_MASTER_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOWNESS, 133, 6), 0.75f).effect(new EffectInstance(Effects.RESISTANCE, 133, 4), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WATER_BREATHING_SWEET_BERRIES_5 = ITEMS.register("water_breathing_sweet_berries_5", () -> new BlockItem(BlockInit.WATER_BREATHING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WATER_BREATHING, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WATER_BREATHING_SWEET_BERRIES_5 = ITEMS.register("long_water_breathing_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_WATER_BREATHING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WATER_BREATHING, 3200, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HEALING_SWEET_BERRIES_5 = ITEMS.register("healing_sweet_berries_5", () -> new BlockItem(BlockInit.HEALING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HEALING_SWEET_BERRIES_5 = ITEMS.register("strong_healing_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_HEALING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_HEALTH, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> HARMING_SWEET_BERRIES_5 = ITEMS.register("harming_sweet_berries_5", () -> new BlockItem(BlockInit.HARMING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1,1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_HARMING_SWEET_BERRIES_5 = ITEMS.register("strong_harming_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_HARMING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.INSTANT_DAMAGE, 1, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> POISON_SWEET_BERRIES_5 = ITEMS.register("poison_sweet_berries_5", () -> new BlockItem(BlockInit.POISON_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.POISON, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_POISON_SWEET_BERRIES_5 = ITEMS.register("long_poison_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_POISON_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.POISON, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_POISON_SWEET_BERRIES_5 = ITEMS.register("strong_poison_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_POISON_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.POISON, 144, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> REGENERATION_SWEET_BERRIES_5 = ITEMS.register("regeneration_sweet_berries_5", () -> new BlockItem(BlockInit.REGENERATION_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.REGENERATION, 300, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_REGENERATION_SWEET_BERRIES_5 = ITEMS.register("long_regeneration_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_REGENERATION_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.REGENERATION, 600, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_REGENERATION_SWEET_BERRIES_5 = ITEMS.register("strong_regeneration_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_REGENERATION_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.REGENERATION, 150, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRENGTH_SWEET_BERRIES_5 = ITEMS.register("strength_sweet_berries_5", () -> new BlockItem(BlockInit.STRENGTH_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(3).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.STRENGTH, 1200, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_STRENGTH_SWEET_BERRIES_5 = ITEMS.register("long_strength_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_STRENGTH_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(4).setAlwaysEdible().fastToEat().saturation(2.9f).effect(new EffectInstance(Effects.STRENGTH, 3200, 1), 0.6f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> STRONG_STRENGTH_SWEET_BERRIES_5 = ITEMS.register("strong_strength_sweet_berries_5", () -> new BlockItem(BlockInit.STRONG_STRENGTH_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.STRENGTH, 600, 2), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> WEAKNESS_SWEET_BERRIES_5 = ITEMS.register("weakness_sweet_berries_5", () -> new BlockItem(BlockInit.WEAKNESS_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.WEAKNESS, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_WEAKNESS_SWEET_BERRIES_5 = ITEMS.register("long_weakness_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_WEAKNESS_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.WEAKNESS, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> SLOW_FALLING_SWEET_BERRIES_5 = ITEMS.register("slow_falling_sweet_berries_5", () -> new BlockItem(BlockInit.SLOW_FALLING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(2).setAlwaysEdible().fastToEat().saturation(1.8f).effect(new EffectInstance(Effects.SLOW_FALLING, 600, 1), 0.45f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));
    public static final RegistryObject<Item> LONG_SLOW_FALLING_SWEET_BERRIES_5 = ITEMS.register("long_slow_falling_sweet_berries_5", () -> new BlockItem(BlockInit.LONG_SLOW_FALLING_BERRY_BUSH_5.get(), new Item.Properties().food(new Food.Builder().hunger(5).setAlwaysEdible().fastToEat().saturation(4f).effect(new EffectInstance(Effects.SLOW_FALLING, 1600, 1), 0.75f).build()).group(PotionBerries.PotionBerriesItemGroup.instance)));


    public enum CustomItemTier implements IItemTier {
        CHRYSOCOLLA(4,2031, 9f, 3.0f, 15, ()-> {
            return Ingredient.fromItems(ItemInit.CHRYSOCOLLA_INGOT.get());
        }),
        SUGILITE(5,2442, 10f, 3.5f, 17, ()-> {
            return Ingredient.fromItems(ItemInit.SUGILITE_INGOT.get());
        }),
        ERYTHRITE(6,2938, 11f, 4.0f, 20, ()-> {
            return Ingredient.fromItems(ItemInit.ERYTHRITE_INGOT.get());
        });

        private final int harvestLevel;
        private final int maxUses;
        private final float efficiency;
        private final float attackDamage;
        private final int enchantability;
        private final LazyValue<Ingredient> repairMaterial;

         CustomItemTier(int harvestLevelIn, int maxUsesIn, float efficiencyIn, float attackDamageIn, int enchantabilityIn, Supplier<Ingredient> repairMaterialIn) {
            this.harvestLevel = harvestLevelIn;
            this.maxUses = maxUsesIn;
            this.efficiency = efficiencyIn;
            this.attackDamage = attackDamageIn;
            this.enchantability = enchantabilityIn;
            this.repairMaterial = new LazyValue<>(repairMaterialIn);
        }

        public int getMaxUses() {
            return this.maxUses;
        }

        public float getEfficiency() {
            return this.efficiency;
        }

        public float getAttackDamage() {
            return this.attackDamage;
        }

        public int getHarvestLevel() {
            return this.harvestLevel;
        }

        public int getEnchantability() {
            return this.enchantability;
        }

        public Ingredient getRepairMaterial() {
            return this.repairMaterial.getValue();
        }
    }

    public enum CustomArmourMaterial implements IArmorMaterial {
        CHRYSOCOLLA(PotionBerries.MOD_ID + ":chrysocolla", 5, new int[] { 7, 9, 11, 7 }, 420, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, 6.9F, () -> {
            return Ingredient.fromItems(ItemInit.CHRYSOCOLLA_INGOT.get());
        }),
        SUGILITE(PotionBerries.MOD_ID + ":sugilite", 5, new int[] { 7, 9, 11, 7 }, 420, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, 6.9F, () -> {
            return Ingredient.fromItems(ItemInit.CHRYSOCOLLA_INGOT.get());
        }),
        ERYTHRITE(PotionBerries.MOD_ID + ":erythrite", 5, new int[] { 7, 9, 11, 7 }, 420, SoundEvents.ITEM_ARMOR_EQUIP_GENERIC, 6.9F, () -> {
            return Ingredient.fromItems(ItemInit.CHRYSOCOLLA_INGOT.get());
        });

        private static final int[] MAX_DAMAGE_ARRAY = new int[] { 16, 16, 16, 16 };
        private final String name;
        private final int maxDamageFactor;
        private final int[] damageReductionAmountArray;
        private final int enchantability;
        private final SoundEvent soundEvent;
        private final float toughness;
        private final LazyValue<Ingredient> repairMaterial;

        private CustomArmourMaterial(String nameIn, int maxDamageFactorIn, int[] damageReductionAmountIn,
                                 int enchantabilityIn, SoundEvent soundEventIn, float toughnessIn,
                                 Supplier<Ingredient> repairMaterialIn) {
            this.name = nameIn;
            this.maxDamageFactor = maxDamageFactorIn;
            this.damageReductionAmountArray = damageReductionAmountIn;
            this.enchantability = enchantabilityIn;
            this.soundEvent = soundEventIn;
            this.toughness = toughnessIn;
            this.repairMaterial = new LazyValue<>(repairMaterialIn);
        }

        @Override
        public int getDurability(EquipmentSlotType slotIn) {
            return MAX_DAMAGE_ARRAY[slotIn.getIndex()] * this.maxDamageFactor;
        }

        @Override
        public int getDamageReductionAmount(EquipmentSlotType slotIn) {
            return this.damageReductionAmountArray[slotIn.getIndex()];
        }

        @Override
        public int getEnchantability() {
            return this.enchantability;
        }

        @Override
        public SoundEvent getSoundEvent() {
            return this.soundEvent;
        }

        @Override
        public Ingredient getRepairMaterial() {
            return this.repairMaterial.getValue();
        }

        @OnlyIn(Dist.CLIENT)
        @Override
        public String getName() {
            return this.name;
        }

        @Override
        public float getToughness() {
            return this.toughness;
        }
    }
}
